apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: payments-ns
spec:
  type: LoadBalancer # Requests a Public IP (ALB in AWS)
  selector:
    app: payments-service
  ports:
    - protocol: TCP
      port: 80 # Port exposed to world
      targetPort: 5000 # Port container is listening on
